spring:
  datasource:
    url: jdbc:h2:./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baselineOnMigrate: true
    baselineVersion: 1

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
    com:
      MatrixCampusSL:
        demo: DEBUG